# Generated by Django 4.1.3 on 2023-02-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=60)),
                ('provider', models.CharField(max_length=60)),
                ('articul', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=60)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
