# Generated by Django 4.2 on 2023-04-19 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('employee', models.CharField(max_length=100, verbose_name='Сотрудник')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('address_comment', models.TextField(blank=True, verbose_name='Комментарий к адресу')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('external_code', models.CharField(blank=True, max_length=50, verbose_name='Внешний код')),
                ('employee', models.CharField(max_length=100, verbose_name='Ответственный сотрудник')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.department', verbose_name='Отдел')),
                ('groups', models.ManyToManyField(blank=True, to='store.group', verbose_name='Группы')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контактное лицо', 'verbose_name_plural': 'Контактные лица'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страна'},
        ),
        migrations.RemoveField(
            model_name='accountingfeatures',
            name='type',
        ),
        migrations.AlterField(
            model_name='accountingfeatures',
            name='tare_capacity',
            field=models.IntegerField(verbose_name='Емкость тары, л.'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contractor_type',
            field=models.CharField(blank=True, choices=[('1', 'Юридическое лицо'), ('2', 'Индивидуальный предприниматель'), ('3', 'Физическое лицо')], max_length=100, verbose_name='Тип контрагента'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='status',
            field=models.CharField(choices=[('1', 'Новый'), ('2', 'Выслано предложение'), ('3', 'Переговоры'), ('4', 'Сделка заключена'), ('5', 'Сделка не заключена')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='accountingFeatures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.accountingfeatures', verbose_name='Особенности учета'),
        ),
        migrations.CreateModel(
            name='Сancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер операции')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('employee', models.CharField(max_length=100, verbose_name='Сотрудник')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('file', models.FileField(blank=True, upload_to='receipt_files/', verbose_name='Файл')),
                ('approved', models.BooleanField(default=False, verbose_name='Проведено')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.contractor', verbose_name='Контрагент')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.department', verbose_name='Отдел')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Позиция')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.project', verbose_name='Проект')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списания',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер операции')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('employee', models.CharField(max_length=100, verbose_name='Сотрудник')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Накладные расходы')),
                ('file', models.FileField(blank=True, upload_to='receipt_files/', verbose_name='Файл')),
                ('approved', models.BooleanField(default=False, verbose_name='Проведено')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.contractor', verbose_name='Контрагент')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.department', verbose_name='Отдел')),
                ('position', models.ManyToManyField(to='store.product', verbose_name='Позиция')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.project', verbose_name='Проект')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Оприходование',
                'verbose_name_plural': 'Оприходования',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер операции')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('employee', models.CharField(max_length=100, verbose_name='Сотрудник')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('file', models.FileField(blank=True, upload_to='receipt_files/', verbose_name='Файл')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.contractor', verbose_name='Контрагент')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.department', verbose_name='Отдел')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Позиция')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Инвентаризация ',
                'verbose_name_plural': 'Инвентаризация ',
            },
        ),
    ]
