# Generated by Django 4.2 on 2023-04-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_inventory_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcode',
            name='main_account',
        ),
    ]
