# Generated by Django 4.1.3 on 2023-04-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'verbose_name': 'Остаток товаров', 'verbose_name_plural': 'Остаток товаров'},
        ),
    ]
